/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alerts: typeof import('./src/components/Alerts.vue')['default']
    AnnotationInput: typeof import('./src/components/AnnotationInput.vue')['default']
    Annotations: typeof import('./src/components/Annotations.vue')['default']
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    EditEssay: typeof import('./src/components/EditEssay.vue')['default']
    EditNote: typeof import('./src/components/EditNote.vue')['default']
    EditSelect: typeof import('./src/components/EditSelect.vue')['default']
    Help: typeof import('./src/components/Help.vue')['default']
    Instructions: typeof import('./src/components/Instructions.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    ResourcePdf: typeof import('./src/components/ResourcePdf.vue')['default']
    Resources: typeof import('./src/components/Resources.vue')['default']
    ResourceUrl: typeof import('./src/components/ResourceUrl.vue')['default']
    ReviewContent: typeof import('./src/components/ReviewContent.vue')['default']
    SendingStatus: typeof import('./src/components/SendingStatus.vue')['default']
    StartupContent: typeof import('./src/components/StartupContent.vue')['default']
    Timer: typeof import('./src/components/Timer.vue')['default']
  }
}
